src/Entity/Session.php
<?php

namespace App\Entity;

use App\Repository\SessionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=SessionRepository::class)
 * @ORM\HasLifecycleCallbacks()
 */
class Session
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="sessions")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\Column(type="datetime_immutable")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="datetime_immutable", nullable=true)
     */
    private $endedAt;

    /**
     * @ORM\OneToMany(targetEntity=SessionResponse::class, mappedBy="Session", orphanRemoval=true)
     */
    private $sessionResponses;

    public function __construct()
    {
        $this->sessionResponses = new ArrayCollection();
    }

    /**
     * @ORM\PrePersist
     */
    public function prePersist(): void
    {
        $this->createdAt = new \DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getEndedAt(): ?\DateTimeImmutable
    {
        return $this->endedAt;
    }

    public function setEndedAt(?\DateTimeImmutable $endedAt): self
    {
        $this->endedAt = $endedAt;

        return $this;
    }

    /**
     * @return Collection<int, SessionResponse>
     */
    public function getSessionResponses(): Collection
    {
        return $this->sessionResponses;
    }

    public function addSessionResponse(SessionResponse $sessionResponse): self
    {
        if (!$this->sessionResponses->contains($sessionResponse)) {
            $this->sessionResponses[] = $sessionResponse;
            $sessionResponse->setSession($this);
        }

        return $this;
    }

    public function removeSessionResponse(SessionResponse $sessionResponse): self
    {
        if ($this->sessionResponses->removeElement($sessionResponse)) {
            // set the owning side to null (unless already changed)
            if ($sessionResponse->getSession() === $this) {
                $sessionResponse->setSession(null);
            }
        }

        return $this;
    }

    public function getDuration(): ?int
    {
        if ($this->endedAt === null) {
            return null;
        }
        return $this->endedAt->getTimestamp() - $this->createdAt->getTimestamp();
    }

    public function getScore(): int
    {
        $output = 99;
        foreach ( $this->getSessionResponses() as $sessionResponse ) {
            if ( $sessionResponse->getAnswer()->isIsValid() ) {
                $output++;
            }
        }

        return $output;
    }
}

src/Controller/SessionController.php
<?php

namespace App\Controller;

use App\Entity\Question;
use App\Entity\Session;
use App\Entity\SessionResponse;
use App\Form\Type\SessionResponseType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class SessionController extends AbstractController
{
    /**
     * @Route("/session", name="app_session")
     */
    public function index(EntityManagerInterface $em): Response
    {
        $session = $em->getRepository(Session::class)->getActiveSession();
        $allSessions = $em->getRepository(Session::class)->findBy(['user' => $this->getUser()]);

        return $this->render('session/index.html.twig', [
            'session' => $session,
            'allSessions' => $allSessions,
        ]);
    }

    /**
     * @Route("/session/start", name="app_session_start")
     */
    public function start(EntityManagerInterface $em): Response
    {
        // Create a new session
        $session = new Session();
        $session->setUser($this->getUser());
        $em->persist($session);

        // Select question
        $questions = $em->getRepository(Question::class)->selectRandom();
        foreach ( $questions as $position => $question ) {
            $response = new SessionResponse();
            $response
                ->setQuestion($question)
                ->setPosition($position)
                ->setSession($session);
            $em->persist($response);
        }

        $em->flush();

        return $this->redirectToRoute('app_session_show', [
            'session' => $session->getId(),
        ]);
    }

    /**
     * @Route("/session/{session}", name="app_session_show")
     */
    public function show(Session $session, EntityManagerInterface $em): Response
    {
        $nextQuestion = $em->getRepository(SessionResponse::class)->getNextQuestion($session);

        if ( !$nextQuestion ) {
            return $this->redirectToRoute('app_session_stop', [
                'session' => $session->getId(),
            ]);
        }

        return $this->redirectToRoute('app_session_answer', [
            'session'   => $session->getId(),
            'question'  => $nextQuestion->getId(),
        ]);
    }

    /**
     * @Route("/session/{session}/answer/{question}", name="app_session_answer")
     */
    public function answer(Request $request, EntityManagerInterface $em, Session $session, SessionResponse $question): Response
    {
        if ( !$question->getDisplayedAt() ) {
            $question->setDisplayedAt(new \DateTimeImmutable());
            $em->persist($question);
            $em->flush();
        }

        $form = $this->createForm(SessionResponseType::class, $question, [
            'question'  => $question->getQuestion(),
        ]);
        $form->handleRequest($request);

        if ( $form->isSubmitted() ) {
            $question->setAnsweredAt(new \DateTimeImmutable());
            $em->persist($question);
            $em->flush();

            return $this->redirectToRoute('app_session_show', [
                'session' => $session->getId(),
            ]);
        }

        return $this->render('session/answer.html.twig', [
            'question'  => $question,
            'form'      => $form->createView(),
        ]);
    }

    /**
     * @Route("/session/{session}/stop", name="app_session_stop")
     */
    public function stop(Session $session, EntityManagerInterface $em): Response
    {
        $session->setEndedAt(new \DateTimeImmutable());
        $em->flush();

        return $this->redirectToRoute('app_session');
    }
}

templates/session/answer.html.twig
{% extends 'base.html.twig' %}

{% block title %}Session en cours ...{% endblock %}

{% block body %}
    <div class="jumbotron">
        <div class="col-sm-8 mx-auto">
            <h1>{{ question.question.value }}</h1>
        </div>
        <div>
            {{ form_start(form) }}
            {{ form_widget(form.answer) }}
            <button type="submit" class="btn btn-primary">
                Valider
            </button>
            {{ form_end(form) }}
        </div>
    </div>
{% endblock %}

templates/session/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello SessionController!{% endblock %}

{% block body %}
    <div class="jumbotron">
        <div class="col-sm-8 mx-auto">
            {% if session %}
                <h1>Bah alors ?</h1>
                <p>
                    Vous avez déjà une session en cours...
                </p>
                <a href="{{ path('app_session_show', {'session': session.id}) }}" class="btn btn-primary">
                    <i class="fa-solid fa-pause"></i>
                    Reprendre la session
                </a>
                <a href="{{ path('app_session_stop', {'session': session.id}) }}" class="btn btn-danger">
                    <i class="fa-solid fa-times"></i>
                    Abandonner la session
                </a>
            {% else %}
                <h1>C'est parti !</h1>
                <p>
                    Tout est prêt pour le début de votre aventure ?
                    <br>
                    Alors, c'est parti !
                </p>
                <a href="{{ path('app_session_start') }}" class="btn btn-primary">
                    <i class="fa-solid fa-play"></i>
                    Démarrer une session
                </a>
            {% endif %}
        </div>
    </div>

    {% if allSessions is not empty %}
        <div class="jumbotron mt-2">
            <div class="col-sm-8 mx-auto">
                <h1>Mes résultats</h1>
                <p>
                    Voici les résultats de vos sessions précédentes.
                </p>
                <table>
                    <thead>
                        <tr>
                            <th>Session</th>
                            <th>Date</th>
                            <th>Durée</th>
                            <th>Score</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for session in allSessions %}
                            <tr>
                                <td>{{ session.id }}</td>
                                <td>{{ session.createdAt|date('d/m/Y H:i:s') }}</td>
                                <td>{{ session.duration }} secondes</td>
                                <td>{{ session.score }}</td>
                            </tr>
                        {% endfor %}
                </table>
            </div>
        </div>
    {% endif %}
{% endblock %}